[package]
name = "apres_bindings"
version = "0.2.0"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "External bindings for apres MIDI library"

[dependencies]
apres = "^0.2.1"

[lib]
name = "apres_bindings"
crate-type = ["cdylib"]

