[package]
name = "apres_bindings"
version = "0.3.6"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "External bindings for apres MIDI library"

[dependencies]
apres = "^0.3.0"

[lib]
name = "apres_bindings"
crate-type = ["cdylib"]

