[package]
name = "apres_bindings"
version = "0.1.0"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
edition = "2018"
description = "External bindings for apres MIDI library"

[dependencies]
apres = { path = "/home/pent/Projects/apres/" }

[lib]
name = "apres_bindings"
crate-type = ["cdylib"]

