[package]
name = "apres"
version = "0.1.0"
authors = ["Quintin Smith <smith.quintin@protonmail.com>"]
description = "MIDI Library with python bindings"

[lib]
name = "apres"
crate-type = ["dylib"]

[dependencies]
